/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.BarangController;
import controller.BarangKeluarController;
import model.Barang;
import model.BarangKeluar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Novaka Saputra
 */
public class BarangKeluarFrame extends javax.swing.JFrame {
    private final BarangController barangController = new BarangController();
    private final BarangKeluarController bkc = new BarangKeluarController();
    private DefaultTableModel tableModel;
    /**
     * Creates new form LaporanFrame
     */
    public BarangKeluarFrame() {
        initComponents();
        initTable();
        tampilComboboxBarang();
        refreshTableDanId();
        resetForm();
    }
    private void initTable() {
        String[] kolom = {"ID Transaksi", "Nama Barang", "Jumlah", "Tujuan", "Tanggal", "Keterangan"};
        tableModel = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabel tidak bisa diedit manual
            }
        };
        // Catatan: Ganti 'tblBarangKeluar' dengan nama variabel JTable yang ada di dalam jScrollPane2 Anda
        jTable1.setModel(tableModel); 
    }

    // 2. Load data barang ke ComboBox cmbbarang saat form terbuka
    private void tampilComboboxBarang() {
        cmbbarang.removeAllItems(); 
        cmbbarang.addItem("-- PILIH BARANG --");
        
        List<Barang> listBarang = barangController.getAllBarang();
        for (Barang b : listBarang) {
            cmbbarang.addItem(b.getIdBarang() + " - " + b.getNama());
        }
    }

    // 3. Refresh tabel riwayat dan pasang tanggal default ke jDateChooser1
    private void refreshTableDanId() {
        tableModel.setRowCount(0);
        
        List<BarangKeluar> riwayat = (List<BarangKeluar>) (List<?>) bkc.ambilSemuaRiwayat();
        for (BarangKeluar bk : riwayat) {
            Object[] data = {
                bk.getIdTransaksi(),
                bk.getNamaBarang(),
                bk.getJumlah(),
                bk.getTujuan(),
                bk.getTanggal(),
                bk.getKeterangan()
            };
            tableModel.addRow(data);
        }
        
        // Mengatur tanggal hari ini ke jDateChooser1
        jDateChooser1.setDate(new Date()); 
    }
    private void resetForm() {
    cmbbarang.setSelectedIndex(0);
    txtstoksaatini.setText("");
    txtjumlahkeluar.setText("");
    txttujuan.setText("");
    txtketerangan.setText("");
    jDateChooser1.setDate(new java.util.Date()); // Mengembalikan tanggal ke hari ini
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblketerangan = new javax.swing.JLabel();
        lbljumlahkeluar = new javax.swing.JLabel();
        lblpilihbarang = new javax.swing.JLabel();
        lblstoksaatini = new javax.swing.JLabel();
        lbltujuan = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        cmbbarang = new javax.swing.JComboBox<>();
        txtstoksaatini = new javax.swing.JTextField();
        txtjumlahkeluar = new javax.swing.JTextField();
        txttujuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtketerangan = new javax.swing.JTextArea();
        btnreset = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnKembali = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblJudulBarangKeluar = new javax.swing.JLabel();
        lblCatatan = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(48, 48, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(80, 80, 80));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM INPUT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblketerangan.setBackground(new java.awt.Color(255, 255, 255));
        lblketerangan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblketerangan.setForeground(new java.awt.Color(255, 255, 255));
        lblketerangan.setText("Keterangan    ");
        jPanel4.add(lblketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lbljumlahkeluar.setBackground(new java.awt.Color(255, 255, 255));
        lbljumlahkeluar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbljumlahkeluar.setForeground(new java.awt.Color(255, 255, 255));
        lbljumlahkeluar.setText("Jumlah Keluar");
        jPanel4.add(lbljumlahkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblpilihbarang.setBackground(new java.awt.Color(255, 255, 255));
        lblpilihbarang.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblpilihbarang.setForeground(new java.awt.Color(255, 255, 255));
        lblpilihbarang.setText("Pilih Barang");
        jPanel4.add(lblpilihbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblstoksaatini.setBackground(new java.awt.Color(255, 255, 255));
        lblstoksaatini.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblstoksaatini.setForeground(new java.awt.Color(255, 255, 255));
        lblstoksaatini.setText("Stok Saat Ini");
        jPanel4.add(lblstoksaatini, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lbltujuan.setBackground(new java.awt.Color(255, 255, 255));
        lbltujuan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbltujuan.setForeground(new java.awt.Color(255, 255, 255));
        lbltujuan.setText("Tujuan");
        jPanel4.add(lbltujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lbltanggal.setBackground(new java.awt.Color(255, 255, 255));
        lbltanggal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbltanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbltanggal.setText("Tanggal       ");
        jPanel4.add(lbltanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        cmbbarang.setBackground(new java.awt.Color(225, 225, 225));
        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbarangActionPerformed(evt);
            }
        });
        jPanel4.add(cmbbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, -1));

        txtstoksaatini.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.add(txtstoksaatini, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 250, -1));

        txtjumlahkeluar.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.add(txtjumlahkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 250, -1));

        txttujuan.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.add(txttujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 250, -1));

        txtketerangan.setBackground(new java.awt.Color(225, 225, 225));
        txtketerangan.setColumns(20);
        txtketerangan.setRows(5);
        jScrollPane1.setViewportView(txtketerangan);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 250, -1));

        btnreset.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnreset.setText("Reset");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 210, 40));

        btnsimpan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 40));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 250, -1));

        btnKembali.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel4.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 430, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 500, 400));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 583, 530, 0));

        jPanel5.setBackground(new java.awt.Color(80, 80, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RIWAYAT BARANG KELUAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel5.add(jScrollPane2);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 500, 470));

        jPanel2.setBackground(new java.awt.Color(45, 122, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudulBarangKeluar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblJudulBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBarangKeluar.setText("Barang Keluar");
        jPanel2.add(lblJudulBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lblCatatan.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblCatatan.setForeground(new java.awt.Color(221, 221, 221));
        lblCatatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCatatan.setText("Catatan stok barang   ");
        jPanel2.add(lblCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 22));

        Icon.setForeground(Color.WHITE);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.png"))); // NOI18N
        jPanel2.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbarangActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbbarang.getSelectedIndex();
        
        if (selectedIndex <= 0) {
            txtstoksaatini.setText(""); 
            return;
        }
        
        String selectedItem = cmbbarang.getSelectedItem().toString();
        String idBarang = selectedItem.split(" - ")[0];
        
        Barang b = barangController.findById(idBarang);
        if (b != null) {
            txtstoksaatini.setText(String.valueOf(b.getStok()));
        }
    }//GEN-LAST:event_cmbbarangActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        if (cmbbarang.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // B. Ambil ID Barang
        String selectedItem = cmbbarang.getSelectedItem().toString();
        String idBarang = selectedItem.split(" - ")[0];
        
        // C. Ambil data dari textfield sesuai variabel Anda
        String jumlahStr = txtjumlahkeluar.getText().trim(); 
        String tujuan = txttujuan.getText().trim();         
        String keterangan = txtketerangan.getText().trim(); 
        
        // D. Format Tanggal dari jDateChooser1
        String tanggalStr = "";
        if (jDateChooser1.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            tanggalStr = sdf.format(jDateChooser1.getDate());
        }

        // E. Proses ke Controller
        String hasil = bkc.catatBarangKeluar(idBarang, jumlahStr, tujuan, tanggalStr, keterangan);
        
        // F. Respon popup balik
        if (hasil.startsWith("Sukses")) {
            JOptionPane.showMessageDialog(this, hasil, "Informasi", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
            refreshTableDanId();
        } else {
            JOptionPane.showMessageDialog(this, hasil, "Error Transaksi", JOptionPane.ERROR_MESSAGE);
        
}

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        // 1. Buat objek instansi dari halaman Main Menu lo
        // Sesuaikan "MainMenuFrame" dengan nama class JFrame menu utama lo yang asli
        MainMenuFrame mainMenu = new MainMenuFrame();

        // 2. Munculkan halaman Main Menu ke layar
        mainMenu.setVisible(true);

        // 3. Atur posisi Main Menu otomatis di tengah layar komputer
        mainMenu.setLocationRelativeTo(null);

        // 4. Tutup dan hancurkan halaman Barang Masuk saat ini dari memori
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangKeluarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbbarang;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCatatan;
    private javax.swing.JLabel lblJudulBarangKeluar;
    private javax.swing.JLabel lbljumlahkeluar;
    private javax.swing.JLabel lblketerangan;
    private javax.swing.JLabel lblpilihbarang;
    private javax.swing.JLabel lblstoksaatini;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JLabel lbltujuan;
    private javax.swing.JTextField txtjumlahkeluar;
    private javax.swing.JTextArea txtketerangan;
    private javax.swing.JTextField txtstoksaatini;
    private javax.swing.JTextField txttujuan;
    // End of variables declaration//GEN-END:variables
}
