/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.BarangDAO;
import dao.BarangMasukDAO;
import model.Barang;
import model.BarangMasuk;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Novaka Saputra
 */
public class LaporanFrame extends javax.swing.JFrame {
    private BarangDAO barangDAO = new BarangDAO();
    private BarangMasukDAO barangMasukDAO = new BarangMasukDAO();
    private DefaultTableModel model;
    /**
     * Creates new form BarangKeluarFrame
     */
    public LaporanFrame() {
        initComponents();
        model = new DefaultTableModel(
        new Object[]{
            "ID Transaksi",
            "Tanggal",
            "Nama Barang",
            "Stok Sebelumnya",
            "Jumlah Masuk",
            "Supplier",
            "Stok Sesudahnya"
        }, 0
    );

        tblLaporan.setModel(model);
        model = (DefaultTableModel) tblLaporan.getModel();
        loadStatistik();
        loadLaporanMasuk();
    }
    
    private void loadStatistik() {
        Totalitem.setText(String.valueOf(barangDAO.getAll().size()));
        TtlBrngMsk.setText(String.valueOf(barangMasukDAO.getAll().size()));
        TtlBrngklr.setText("0");
}
    
    private void loadLaporanMasuk() {
        model.setRowCount(0);
        List<BarangMasuk> list = barangMasukDAO.getAll();

        for (BarangMasuk bm : list) {
            Barang barang = barangDAO.findById(bm.getIdBarang());
            int stokSesudah = 0;

            if (barang != null) {
                stokSesudah = barang.getStok();
            }

            int stokSebelum = stokSesudah - bm.getJumlah();
            model.addRow(new Object[]{
                bm.getIdTransaksi(),
                bm.getTanggal(),
                bm.getNamaBarang(),
                stokSebelum,
                bm.getJumlah(),
                bm.getSupplier(),
                stokSesudah
            });
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelJudul = new javax.swing.JPanel();
        lblJudulLaporan = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitleTotalItem = new javax.swing.JLabel();
        Totalitem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitleBarangMasuk = new javax.swing.JLabel();
        TtlBrngMsk = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTitleBarangKeluar = new javax.swing.JLabel();
        TtlBrngklr = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));

        JpanelJudul.setBackground(new java.awt.Color(45, 122, 80));

        lblJudulLaporan.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        lblJudulLaporan.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulLaporan.setText("Laporan Barang");

        Background.setBackground(new java.awt.Color(48, 48, 47));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(80, 80, 80));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitleTotalItem.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblTitleTotalItem.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleTotalItem.setText("Total Item");

        Totalitem.setForeground(new java.awt.Color(255, 255, 255));
        Totalitem.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitleTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Totalitem, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitleTotalItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Totalitem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 90));

        jPanel2.setBackground(new java.awt.Color(80, 80, 80));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitleBarangMasuk.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblTitleBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleBarangMasuk.setText("Barang Masuk");

        TtlBrngMsk.setForeground(new java.awt.Color(255, 255, 255));
        TtlBrngMsk.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitleBarangMasuk)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TtlBrngMsk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitleBarangMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TtlBrngMsk)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 90));

        jPanel4.setBackground(new java.awt.Color(80, 80, 80));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitleBarangKeluar.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblTitleBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleBarangKeluar.setText("Barang Keluar");

        TtlBrngklr.setBackground(new java.awt.Color(255, 255, 255));
        TtlBrngklr.setForeground(new java.awt.Color(255, 255, 255));
        TtlBrngklr.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitleBarangKeluar)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TtlBrngklr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitleBarangKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TtlBrngklr)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 160, 90));

        btnRefresh.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        Background.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        btnClose.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnClose.setText("KEMBALI");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        Background.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        jPanel3.setBackground(new java.awt.Color(80, 80, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RIWAYAT LAPORAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLaporan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12))); // NOI18N
        tblLaporan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Nama Barang", "Stok Sebelumnya", "Jumlah Masuk", "Supplier", "Stok Sesudahnya"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLaporan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 760, 270));

        Background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 780, 300));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.png"))); // NOI18N

        javax.swing.GroupLayout JpanelJudulLayout = new javax.swing.GroupLayout(JpanelJudul);
        JpanelJudul.setLayout(JpanelJudulLayout);
        JpanelJudulLayout.setHorizontalGroup(
            JpanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelJudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelJudulLayout.createSequentialGroup()
                        .addComponent(lblJudulLaporan)
                        .addGap(318, 318, 318))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelJudulLayout.createSequentialGroup()
                        .addComponent(Icon)
                        .addGap(356, 356, 356))))
        );
        JpanelJudulLayout.setVerticalGroup(
            JpanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelJudulLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJudulLaporan)
                .addGap(18, 18, 18)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadStatistik();
        loadLaporanMasuk();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        MainMenuFrame mainMenu = new MainMenuFrame();
        mainMenu.setVisible(true);
        mainMenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel JpanelJudul;
    private javax.swing.JLabel Totalitem;
    private javax.swing.JLabel TtlBrngMsk;
    private javax.swing.JLabel TtlBrngklr;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulLaporan;
    private javax.swing.JLabel lblTitleBarangKeluar;
    private javax.swing.JLabel lblTitleBarangMasuk;
    private javax.swing.JLabel lblTitleTotalItem;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
